### ISSUE TITLE
melonDS

### ISSUE THREAD

**Issue by spotanjo3** [Hydr8gon/melonDS#2]
Awesome job. I hope that your emulator will improvement greatly in speed for Switch. I am not fan of overclocking, thought. So I will wait for your improvement in speed. Good job again!

**Comment by Hydr8gon** [comment]
Lol thanks, but this isn't really an issue :laughing: check the [GBAtemp thread](https://gbatemp.net/threads/melonds-for-switch.518300/) for fun discussion times. Closing~

**Comment by Hydr8gon** [comment]
Lol thanks, but this isn't really an issue! :laughing: Check the [GBAtemp thread](https://gbatemp.net/threads/melonds-for-switch.518300/) for fun discussion times. Closing~
