### ISSUE TITLE
Enable vectorization

### ISSUE THREAD

**Issue by dirocco** [Hydr8gon/melonDS#3]
GCC doesn't vectorize loops in O2.  You should enable it by adding -ftree-vectorize or changing the optimization level to O3 (which also unrolls loops, among other things).

Here are some counts of vector register usage from objdump:

`O2:  v0: 442  q0: 141`

`O2 -ftree-vectorize: v0: 699 q0: 281`

`O3: v0: 843  q0: 284 `

Adding -funsafe-math-optimizations -ffast-math also changes code generation significantly but might break things.  It's worth a shot.

**Comment by dirocco** [comment]
I tried building melonDS 0.7.4 and top of tree with no modifications but kept getting error 2168-0001 on the switch even though I was able to build retroarch+mgba on the same devkitpro setup.  So I couldn't test these settings.

**Comment by Hydr8gon** [comment]
Oh yeah, something in the newest libnx/switch-mesa breaks my UI. I keep forgetting to look into it; I just downgraded for now.

Regarding the optimizations, I've tried them in the past and they didn't seem to make much of a difference. Might've been before overclocking though, so it wasn't as noticeable. -Ofast, which includes all these optimizations and more, seems to give a bit of a boost.
