### ISSUE TITLE
Lags on switch

### ISSUE THREAD

**Issue by XiNaru** [Hydr8gon/melonDS#4]
Hey,

I tried to use the emulator on the switch, and he's okay. the firmeware I have set extra in German.

unfortunately, the games were very strong and therefore hardly playable. even the overcocking and frameraten skipping does not bring much

is there any hint for a good playable emulator setting on the switch?

**Comment by Hydr8gon** [comment]
Unfortunately a lot of games won't be able to reach full speed with the emulator in its current state. Some things are being worked on but it could still take a while before we get significantly better speeds.
