### ISSUE TITLE
Update to MelonDS 0.8 for OpenGL

### ISSUE THREAD

**Issue by UnicornsOnLSD** [Hydr8gon/melonDS#5]
OpenGL would bring huge performance improvements and could potentially make games run at full speed. Is there an ETA on the Switch port of 0.8? I expect it to take a while since the whole renderer has changed :)

**Comment by Hydr8gon** [comment]
I've got it running, but there are some problems (namely polygons randomly not rendering) and performance isn't as good as you would expect. It's a bit faster in some scenarios, a bit slower in others. Likely the nouveau-based GPU drivers we have can't keep up with the fancy stuff the renderer is pulling. Anyways, not sure if it's worth a release with the current issues. We're looking into it, but it's probably a driver bug.

**Comment by FM1337** [comment]
> Anyways, not sure if it's worth a release with the current issues.

Yeah I agree with you there, problem is people seem to be way to hyped up over this update thinking that it's the holy grail and it will solve all their problems, if they see that this isn't the case I fear that you may get some rowdy people that could cause unnecessary drama.

Even if it takes longer, it's probably best to iron out all the bugs you can find related to the opengl renderer before releasing the next version to the public.

Anyway good luck and thank you.

**Comment by UnicornsOnLSD** [comment]
I'll take your word on it. Damn the DS for being so awkward lol :/
