### ISSUE TITLE
i cant control melonDS with joycon

### ISSUE THREAD

**Issue by silveromg** [Hydr8gon/melonDS#9]
my system version is 9.0.1(Atmosphere)
i installed the lastest version but i cant control it with my joycon
i can control with screen only
plz fix to use joycon in 9.0 :(

**Comment by Hydr8gon** [comment]
Oh right, they changed the way input works in 9.0.x. Try this build, and let me know if it works.

[melonds-0.8.3.zip](https://github.com/Hydr8gon/melonDS/files/3721261/melonds-0.8.3.zip)

**Comment by silveromg** [comment]
i already tried the latest version you released(0.8.3) but it didnt work

**Comment by Hydr8gon** [comment]
This is a new build. I recompiled it with the latest libnx so the input issues should be fixed.

**Comment by silveromg** [comment]
it works really well 
thank you so much 👍
